
package test;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esper
 */
public class Fitness extends javax.swing.JFrame {

    /**
     * Creates new form Fitness
     */
//    private DefaultTableModel dt;
    private int id = 1000;
//    private String name,surname,mat;
//    private String service,type,gender,dater,dated;
    String[] arrID = new String[300];
    String[] arrHeight = new String[300];
    String[] arrName = new String[300];
    String[] arrSurname = new String[300];
    String[] arrService = new String[300];
    String[] arrType = new String[300];
    String[] arrGender = new String[300];
    public static String[] arrPrice = new String[300];
    String[] arrDate = new String[300];
    String[] arrD = new String[300];
    String [] arrDateR= new String [300];
    String [] arrDateD= new String [300];
    int cur = 0, tblRows = 0;
    // kena deklaruar varjablat qe i mban vlerat per momentin deri kur ti fusim te tabela
    private int i;
    
    public void add(){
        try{
            
            int time = 0;
          switch(Service.getSelectedIndex()){
              case 0:
                  time=1;
                  break;
              case 1:
                  time=3;
                  break;
              case 2:
                  time=6;
                  break;
              case 3:
                  time=12;
                  break;
          }
// kjo esht nje metod qe ben shtesen e vlerave nga secilla fush ne array 
          int month=(Date.getDate().getMonth()+1)+time;
          int year=(Date.getDate().getYear()+1900)+month/12;
          if (month>12)
          month=month%12;
          
            
       arrID[cur] = txtid.getText();
//       jTable.setValueAt(cur, tblRows) = arrID[cur];

        
       arrHeight[cur] = Height.getText();
       arrName[cur] = Name.getText();
       arrSurname[cur] = Surname.getText();
       arrService[cur] = Service.getSelectedItem().toString();
       arrType[cur] = Nr.getText();
       arrDate[cur] = (Date.getDate().getMonth()+1)+"-"+Date.getDate().getDate()+"-"+(Date.getDate().getYear()+1900);
       arrD[cur] = month+"-"+Date.getDate().getDate()+"-"+year;
       arrDateR[cur] = Date.getDate().toString();
       arrDateD[cur] = Date.getDate().toString();
       
       // mer textin nga fusha pare nga e dyta edhe nga tjera edhe i fut ne secillen ne array prej te pares deri te e fundit
       
       if(man.isSelected()){
       arrGender[cur] = "Male";
       }else if(woman.isSelected()){
       arrGender[cur] = "Female";
       }else
           arrGender[cur]=null;
       
    
       switch(arrService[cur]){
           case "One Month": arrPrice[cur] = "35$";
           break;
           case "Tree Months": arrPrice[cur] = "100$";
           break;
           case "Six Months": arrPrice[cur] = "180$";
           break;
           case "One Year": arrPrice[cur] = "240$";
           break;
       }
       cur++;
        }catch(Exception e){
            System.out.println("Yess");
        }
       
       // kena perdor nje kusht per selectin qe na jep nje cmin te ndryshem nga secilli emer
    }
    
//    public void display(){
//       dt.addRow(row);
//       for(int i=0;i<7;i++){
//       JOptionPane.showMessageDialog(null, data[cur-1][i]);
//       }
//    }
   
    public Fitness() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    SecondTable st = new SecondTable();
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        Height = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Surname = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        searchID = new javax.swing.JComboBox<>();
        man = new javax.swing.JCheckBox();
        woman = new javax.swing.JCheckBox();
        refresh = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        Service = new javax.swing.JComboBox<>();
        Nr = new javax.swing.JTextField();
        change = new javax.swing.JButton();
        Show = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Date = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 53, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Height:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 153, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 83, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Surname:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 113, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Phone Nr:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 233, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Service:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 193, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Select:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, 16));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(153, 0, 153));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 50, 120, -1));

        Height.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightActionPerformed(evt);
            }
        });
        Height.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HeightKeyTyped(evt);
            }
        });
        getContentPane().add(Height, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 150, 120, -1));

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 80, 120, -1));

        Surname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SurnameKeyTyped(evt);
            }
        });
        getContentPane().add(Surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 110, 120, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 120, -1));

        searchID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "name", "surname" }));
        searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDActionPerformed(evt);
            }
        });
        getContentPane().add(searchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 120, -1));

        man.setText("men");
        man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manActionPerformed(evt);
            }
        });
        getContentPane().add(man, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 311, 60, -1));

        woman.setText("woman");
        woman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                womanActionPerformed(evt);
            }
        });
        getContentPane().add(woman, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 311, -1, -1));

        refresh.setBackground(new java.awt.Color(255, 153, 0));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        refresh.setText("Refresh");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 120, 30));

        add.setBackground(new java.awt.Color(255, 102, 0));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        add.setText("  Add ");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 120, 30));

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kosh.png"))); // NOI18N
        delete.setText("  Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 120, 30));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnSearch.setText(" Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 120, 30));

        jTable.setForeground(new java.awt.Color(102, 204, 0));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Height", "Service", "Nr", "Gender", "Price", "Date R", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setGridColor(new java.awt.Color(153, 0, 153));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 50, 605, 276));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Gender:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 311, -1, -1));

        Service.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Service.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One Month", "Tree Months", "Six Months", "One Year" }));
        Service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceActionPerformed(evt);
            }
        });
        getContentPane().add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 190, 120, -1));

        Nr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NrActionPerformed(evt);
            }
        });
        Nr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NrKeyTyped(evt);
            }
        });
        getContentPane().add(Nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 230, 120, -1));

        change.setBackground(new java.awt.Color(204, 204, 204));
        change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings2.png"))); // NOI18N
        change.setText("Change");
        change.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeMouseExited(evt);
            }
        });
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        getContentPane().add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, 30));

        Show.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syri.png"))); // NOI18N
        Show.setText("  Show  Profile ");
        Show.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        getContentPane().add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 160, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list.png"))); // NOI18N
        jButton1.setText("List Members    ");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 160, 20));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 271, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 272, 61, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1111111.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
       add.setBackground(Color.white);
        
        
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
       add.setBackground(Color.orange);
    }//GEN-LAST:event_addMouseExited

    private void changeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseEntered
       change.setBackground(Color.white);
    }//GEN-LAST:event_changeMouseEntered

    private void changeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseExited
        change.setBackground(Color.orange);
    }//GEN-LAST:event_changeMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(Color.white);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
         delete.setBackground(Color.orange);
    }//GEN-LAST:event_deleteMouseExited

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
//        btnn4.setBackground(new java.awt.Color(255,255,255));
           refresh.setBackground(Color.white);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
         refresh.setBackground(Color.orange);
    }//GEN-LAST:event_refreshMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
         btnSearch.setBackground(Color.white);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        btnSearch.setBackground(Color.orange);
    }//GEN-LAST:event_btnSearchMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
       
    }//GEN-LAST:event_jTableMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
//        add.setBackground(new java.awt.Color(255,255,255));  
        add.setBackground(Color.blue);
       
        
      try{  
          
        add();
       Object [] row = {arrID[cur-1],arrName[cur-1],arrSurname[cur-1],
                        arrHeight[cur-1],arrService[cur-1], arrType[cur-1],
                        arrGender[cur-1], arrPrice[cur-1],arrDate[cur-1],
                        arrD[cur-1] , arrDateR[cur-1], arrDateD[cur-1] };

       DefaultTableModel model = (DefaultTableModel) jTable.getModel();
       DefaultTableModel model2 = (DefaultTableModel) st.jTable1.getModel();
       DefaultTableModel model3 = (DefaultTableModel) st.jTable2.getModel();
       
       if(!row[6].equals(null)){
           model.addRow(row);
       
       if(row[6].equals("Male"))
           model2.addRow(row);
      
       if(row[6].equals("Female"))
           model3.addRow(row);
      
       tblRows++;
       }
       txtid.setText(Integer.toString(++id));
       
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,"Please complete all components. ");
         
      }
    }//GEN-LAST:event_addActionPerformed

    private void manActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manActionPerformed
        woman.setSelected(false);
    }//GEN-LAST:event_manActionPerformed

    private void womanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_womanActionPerformed
    man.setSelected(false);
    }//GEN-LAST:event_womanActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        
        DefaultTableModel model= (DefaultTableModel) jTable.getModel();
            
        
            if(jTable.getSelectedRow()==-1){
            if (jTable.getRowCount()==0){
                // qofse selectet row esht bosh tabela nuk shfaq as nje gje
                JOptionPane.showMessageDialog(null, "Table is empty");
            }else{
                JOptionPane.showMessageDialog(null, "Please select an Item");
            }
            }else{
            model.setValueAt(Name.getText(), jTable.getSelectedRow(), 1);
            model.setValueAt(Surname.getText(), jTable.getSelectedRow(), 2);
            model.setValueAt(Height.getText(), jTable.getSelectedRow(), 3);
            model.setValueAt(Service.getSelectedItem().toString(), jTable.getSelectedRow(), 4);
            model.setValueAt(Nr.getText().toString(), jTable.getSelectedRow(), 5);
            String Gender = null;
            
            if(man.isSelected()==true)
                Gender="Male";
            else if(woman.isSelected()==true)
                Gender="Female";
            model.setValueAt(Gender, jTable.getSelectedRow(), 6);
            
            
            // kjo esht pjesa qe rimbush pjesat ne te majten me vlerat e rreshtit te selektuar ne tabel 
        
    }
        
    }//GEN-LAST:event_changeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try{
            int SelectedRow = jTable.getSelectedRow();
            jTable.addNotify();
   //delete kap ate qe seleksionon ne tabel dhe e fshin 
            ((DefaultTableModel)jTable.getModel()).removeRow(SelectedRow);
            ((DefaultTableModel)jTable.getModel()).getTableModelListeners();
        }catch(Exception e){
            System.out.println("Error");
//            JOptionPane.showConfirmDialog(man, "No items left to delete.");
          
            JOptionPane.showMessageDialog(null, "Please select an Item");
            
            
        }
       
        
 

        
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

        Height.setText("");
        Name.setText("");
        Surname.setText("");
        Service.setSelectedIndex(0);
        Nr.setText("");
        arrGender.equals("");
        woman.setSelected(false);
        man.setSelected(false);
        
        
        
    }//GEN-LAST:event_refreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       
        
        int index = 0;
        String item = (String) searchID.getSelectedItem();
        switch(item){
            case "id":
                for (int j = 0; j < arrID.length; j++) {
                    if(txtSearch.getText().equals(arrID[j]))
                        index = j;
               }
                break;
            case "name":
                
                for (int j = 0; j < arrName.length; j++) {
                    if(txtSearch.getText().equals(arrName[j]))
                        index = j;
                }
                break;
             case "surname":
                for (int j = 0; j < arrSurname.length; j++) {
                    if(txtSearch.getText().equals(arrSurname[j]))
                        index=j++;
                }
                break;
        }  
        // kjo esht pjesa e serchit qe kerkon si pas id emrin dhe mbiemrit esht ber me nje loop qe qofse e gjen id e kerkuar do shfaq indextin qe kan vlerat ktu posht
        
        String ID = arrID[index];
        String Height = arrHeight[index];
        String Name = arrName[index];
        String Surname = arrSurname[index];
        String Service = arrService[index];
        String Type = arrType[index];
        String Gender = arrGender[index];
        String Price =arrPrice[index];
        String DateR =arrDateR[index];
        String DateD =arrDateD[index];
        ProfileUssers pu = new ProfileUssers(ID,Height,Name,Surname,Service,Type,Gender,Price,DateR,DateD);
        pu.setVisible(true);
        System.out.println(""+DateR);
        System.out.println(""+DateD);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void ServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed

        try{
        String ID = arrID[jTable.getSelectedRow()];
        String height = arrHeight[jTable.getSelectedRow()];
        String namee = arrName[jTable.getSelectedRow()];
        String surnam = arrSurname[jTable.getSelectedRow()];
        String servic = arrService[jTable.getSelectedRow()];
        String Type = arrType[jTable.getSelectedRow()];
        String Gender = arrGender[jTable.getSelectedRow()];
        String Price = arrPrice[jTable.getSelectedRow()];
        String DateR = (String)jTable.getValueAt(jTable.getSelectedRow(), 8);
        String DateD = (String)jTable.getValueAt(jTable.getSelectedRow(), 9);
            
//        // mer te dhenat nga reshti zgjedhur ne tabel edhe i shfaq ne profilin e ussersit te reshti posht 
        ProfileUssers pu = new ProfileUssers(ID,height,namee,surnam,servic,Type,Gender,Price,DateR,DateD);
        pu.setVisible(true);
        }catch(Exception e){
//            JOptionPane.showConfirmDialog(man, "No item selected.");
              JOptionPane.showMessageDialog(null,"No item Selected");
        }
    }//GEN-LAST:event_ShowActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        
        
        
        
    }//GEN-LAST:event_txtidActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        txtid.setText(Integer.toString(id));
    }//GEN-LAST:event_formComponentShown

    private void HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightActionPerformed
        
    }//GEN-LAST:event_HeightActionPerformed

    private void HeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HeightKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        
    }
    }//GEN-LAST:event_HeightKeyTyped

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)){
            evt.consume();
        
    }
    }//GEN-LAST:event_NameKeyTyped

    private void SurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SurnameKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)){
            evt.consume();
        
    }
    }//GEN-LAST:event_SurnameKeyTyped

    private void NrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NrActionPerformed
       
    }//GEN-LAST:event_NrActionPerformed

    private void NrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NrKeyTyped
         char c = evt.getKeyChar();
        if(Character.isLetter(c)){  
            evt.consume();
    }//GEN-LAST:event_NrKeyTyped
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//             System.out.println("Rows "+jTable.getRowCount());
//             
//            for (int row = 0; row <jTable.getRowCount(); row++) {
//                if(!jTable.getValueAt(row, 6).equals("Male")){
//                    
//                ((DefaultTableModel)jTable.getModel()).removeRow(row);
////                ((DefaultTableModel)jTable.getModel()).getTableModelListeners();
//                 ((DefaultTableModel)jTable.getModel()).equals("man");
//                }
//                   System.out.print(row+" ");
//            }
            st.setVisible(true);
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIDActionPerformed
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
//        classC C= new classC();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fitness().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker Date;
    private javax.swing.JTextField Height;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Nr;
    private javax.swing.JComboBox<String> Service;
    private javax.swing.JButton Show;
    private javax.swing.JTextField Surname;
    private javax.swing.JButton add;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton change;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.ButtonGroup jrbg;
    private javax.swing.JCheckBox man;
    private javax.swing.JButton refresh;
    private javax.swing.JComboBox<String> searchID;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtid;
    private javax.swing.JCheckBox woman;
    // End of variables declaration//GEN-END:variables
}
